name: 'skypoints'
version: '1.0.0'
config-version: 2

profile: 'skypoints'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  skypoints:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  skypoints:
    +quote_columns: false
